version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-downloader-app
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge